# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: MSBuild@1
  inputs:
    solution: '**/Webshop_db.sqlproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/try-db-code-web.csproj'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/try-db-code-web/bin/Debug/net5.0
    artifactName: WebApp-code
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/Webshop_db/bin/Debug
    artifactName: WebApp-db