# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: MSBuild@1
  inputs:
    solution: '**/Webshop_db.sqlproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/try-db-code-web.csproj'
- task: AzurePowerShell@2
  displayName: Azure PowerShell script: FilePath
  inputs:
    azureSubscription: '$(azure-subscription)'
    ScriptPath: '$(System.DefaultWorkingDirectory)\deployment_scripts\SetAzureFirewallRule.ps1'
    ScriptArguments: '$(DbServerName) $(ResourceGroup)'
    azurePowerShellVersion: LatestVersion
- task: CmdLine@2
  inputs:
    script: |
      "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150\sqlpackage.exe" ^
      /action:script ^
      /sourcefile:$(System.DefaultWorkingDirectory)/Webshop_db/bin/Debug/Webshop_db.dacpac ^
      /outputpath:$(System.DefaultWorkingDirectory)/Webshop_db/bin/Debug/db-script.sql ^
      /TargetConnectionString:"$(target-server-connection)"
- task: AzurePowerShell@2
  displayName: Azure PowerShell script: FilePath
  inputs:
    azureSubscription: '$(azure-subscription)'
    ScriptPath: '$(System.DefaultWorkingDirectory)\deployment_scripts\RemoveAzureFirewallRule.ps1'
    ScriptArguments: '$(DbServerName) $(ResourceGroup)'
    azurePowerShellVersion: LatestVersion
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/try-db-code-web/bin/Debug/net5.0/publish.zip
    artifactName: WebApp-code
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/Webshop_db/bin/Debug
    artifactName: WebApp-db